### PR TITLE
Update the implementation for compatibility with Elixir 1.2's Task

### PR DESCRIPTION
**Pull request by alco**

### CODE REVIEW

**Comment by MSch** [comment]
@alco can you update the `mix.exs`?

**Comment by alco** [comment]
@MSch I have updated the Elixir version requirement, leaving it up to you to decide on the version number.

**Comment by alco** [comment]
You want to wait for Elixir v1.2 before merging this?

**Comment by MSch** [comment]
@alco I think it's fine if master is already elixir 1.2 only, as long as we don't release it

**Pull request merged**
